apiVersion: v1
kind: ConfigMap
metadata:
  name: router-configmap
data:
  config.yaml: |
    # Versioning makes it easier to track changes over time:
    config_version: "1.0"

    #################################################
    #  GLOBAL / SHARED CONFIGURATION
    #################################################
    global:
      model_map:
        weak:
          endpoint: "http://some-inference-service:8000/weak"
          model_id: "openai/gpt-3.5-turbo"
        strong:
          endpoint: "http://some-inference-service:8000/strong"
          model_id: "openai/gpt-4"

    #################################################
    #  CONTROLLERS CONFIG
    #################################################
    controllers:
      # ------------------------------------------------
      #  RouteLLM Controller
      # ------------------------------------------------
      routellm:
        controller_type: "routellm"
        embedding_provider: "huggingface"  # or "openai"
        embedding_model: "intfloat/e5-base-v2"

        # Example: using Matrix Factorization
        routing_algorithm: "mf"
        threshold: 0.3

        config:
          sw_ranking:
            arena_battle_datasets:
              - "lmsys/lmsys-arena-human-preference-55k"
              - "routellm/gpt4_judge_battles"
            arena_embedding_datasets:
              - "routellm/arena_battles_embeddings"
              - "routellm/gpt4_judge_battles_embeddings"
          causal_llm:
            # TODO: Update checkpoint path if needed
            checkpoint_path: "routellm/causal_llm_gpt4_augmented"
          bert:
            # TODO: Update checkpoint path if needed
            checkpoint_path: "routellm/bert_gpt4_augmented"
          mf:
            checkpoint_path: "madison-evans/routellm-e5-base-v2"
            use_openai_embeddings: false
            embedding_model_name: "intfloat/e5-base-v2"

      # ------------------------------------------------
      #  Semantic Router Controller
      # ------------------------------------------------
      semantic_router:
        controller_type: "semantic_router"
        embedding_provider: "huggingface"

        routes:
          - name: "strong"
            utterances:
              - "You have a 5x5 grid. Determine the number of unique paths..."
              - "Prove the Pythagorean theorem..."
              - "Explain the Calvin cycle and its role in photosynthesis."
              - "What are the key postulates of quantum mechanics...?"
              - "If a train departs from City A..."
              - "Outline the steps to derive the Navier-Stokes equations..."
              - "Discuss the ethical implications of deploying AI..."

          - name: "weak"
            utterances:
              - "Hello, how are you today?"
              - "Can you tell me a funny joke?"
              - "What's the temperature in New York City?"
              - "What's 2 + 2?"
              - "Play some relaxing music..."
              - "What is the population of Japan?"
              - "Set a timer for 5 minutes..."
              - "What's the best way to bake a chocolate cake?"
              - "Tell me the name of the tallest building in the world."
