model_map:
  weak:
    endpoint: "http://some-inference-service:8000/weak"
    model_id: "openai/gpt-3.5-turbo"
  strong:
    endpoint: "http://some-inference-service:8000/strong"
    model_id: "openai/gpt-4"

controller_config_path: "/app/configs/routellm_config.yaml"
# Or use semantic_router_config.yaml if desired
