apiVersion: v1
kind: Service
metadata:
  name: router-microservice-svc
spec:
  type: ClusterIP
  selector:
    app: router-microservice
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
