apiVersion: v1
kind: ConfigMap
metadata:
  name: router-config
data:
  config.yaml: |-
    # Global config for your router microservice
    model_map:
      weak:
        endpoint: "http://some-inference-service:8000/weak"
        model_id: "openai/gpt-3.5-turbo"
      strong:
        endpoint: "http://some-inference-service:8000/strong"
        model_id: "openai/gpt-4"

    # Select controller configuration:
    # To test RouteLLM, use:
    controller_config_path: "/app/configs/routellm_config.yaml"
    # To test semantic router, you could change the above line to:
    # controller_config_path: "/app/configs/semantic_router_config.yaml"
