apiVersion: v1
kind: ConfigMap
metadata:
  name: router-configmap
data:
  config.yaml: |
    model_map:
      weak:
        endpoint: "http://some-inference-service:8000/weak"
        model_id: "openai/gpt-3.5-turbo"
      strong:
        endpoint: "http://some-inference-service:8000/strong"
        model_id: "openai/gpt-4"

    controller_config_path: "integrations/controllers/routellm/config.yaml"
