apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-microservice
  template:
    metadata:
      labels:
        app: router-microservice
    spec:
      containers:
      - name: router
        image: "opea/router:latest"
        ports:
          - containerPort: 6000

        # Environment variables can override or supplement config.yaml:
        env:
          - name: CONFIG_PATH
            value: /app/config.yaml

          # Example for HF_TOKEN from a K8s Secret
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: huggingface-secrets
                key: hf-token

          # Example for OPENAI_API_KEY from a K8s Secret
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: openai-secrets
                key: openai-api-key

        volumeMounts:
          - name: router-config
            mountPath: /app/config.yaml
            subPath: config.yaml

      volumes:
      - name: router-config
        configMap:
          name: router-configmap
