apiVersion: v1
kind: Service
metadata:
  name: router-service
  labels:
    app: router
spec:
  type: ClusterIP
  selector:
    app: router
  ports:
    - port: 6000
      targetPort: 6000
      protocol: TCP
