apiVersion: v1
kind: ConfigMap
metadata:
  name: semanticrouter-configmap
data:
  semantic_router_config.yaml: |
    controller_type: "semantic_router"
    embedding_provider: "huggingface"

    routes:
      - name: "strong"
        utterances:
          - "You have a 5x5 grid. Determine the number of unique paths..."
          - "Prove the Pythagorean theorem..."
          - "Explain the Calvin cycle and its role in photosynthesis."
          - "What are the key postulates of quantum mechanics...?"
          - "If a train departs from City A..."
          - "Outline the steps to derive the Navier-Stokes equations..."
          - "Discuss the ethical implications of deploying AI..."
      - name: "weak"
        utterances:
          - "Hello, how are you today?"
          - "Can you tell me a funny joke?"
          - "What's the temperature in New York City?"
          - "What's 2 + 2?"
          - "Play some relaxing music..."
          - "What is the population of Japan?"
          - "Set a timer for 5 minutes..."
          - "What's the best way to bake a chocolate cake?"
          - "Tell me the name of the tallest building in the world."
