controller_type: "routellm" # specify which typ of controller to use ("routellm" | "semantic_router")
embedding_provider: "huggingface" # specify provider for embedding model ("openai" | "huggingface")
embedding_model: "intfloat/e5-base-v2"

# The following params are relevant only for routellm controller 

routing_algorithm: "mf" # specify the routing algorithm 
threshold: 0.3
config:
  sw_ranking:
    arena_battle_datasets:
      - "lmsys/lmsys-arena-human-preference-55k"
      - "routellm/gpt4_judge_battles"
    arena_embedding_datasets:
      - "routellm/arena_battles_embeddings"
      - "routellm/gpt4_judge_battles_embeddings"
  causal_llm:
    checkpoint_path: "routellm/causal_llm_gpt4_augmented"
  bert:
    checkpoint_path: "routellm/bert_gpt4_augmented"
  mf:
    checkpoint_path: "madison-evans/routellm-e5-base-v2"
    use_openai_embeddings: false
    embedding_model_name: "intfloat/e5-base-v2"
