# Global config for router microservice
model_map:
  weak:
    endpoint: "http://some-inference-service:8000/weak"
    model_id: "openai/gpt-3.5-turbo"
  strong:
    endpoint: "http://some-inference-service:8000/strong"
    model_id: "openai/gpt-4"

controller_config_paths:
  routellm:   "/app/configs/routellm_config.yaml"
  semantic_router: "/app/configs/semantic_router_config.yaml"
