controller_type: "semantic_router"
embedding_provider: "huggingface"
routes:
  - name: "strong"
    utterances:
      - "You have a 5x5 grid. Determine the number of unique paths from the top-left corner to the bottom-right corner."
      - "Prove the Pythagorean theorem using geometric arguments and algebraic principles."
      - "Explain the Calvin cycle and its role in photosynthesis."
      - "What are the key postulates of quantum mechanics, and how do they relate to wave-particle duality?"
      - "If a train departs from City A at 8:00 AM traveling at 60 mph and another train departs from City B at 9:00 AM traveling at 80 mph, when and where will they meet?"
      - "Describe the differences between supervised, unsupervised, and reinforcement learning, and provide examples of each."
      - "Outline the steps to derive the Navier-Stokes equations from the conservation of momentum."
      - "Discuss the ethical implications of deploying AI in healthcare decision-making systems."

  - name: "weak"
    utterances:
      - "Hello, how are you today?"
      - "Can you tell me a funny joke to lighten the mood?"
      - "What's the temperature in New York City right now?"
      - "What's 2 + 2?"
      - "Play some relaxing music for me."
      - "What is the population of Japan?"
      - "Set a timer for 5 minutes, please."
      - "What's the best way to bake a chocolate cake?"
      - "Tell me the name of the tallest building in the world."
      - "Can you recommend a good movie to watch this weekend?"
